[project]
name = "ftk"
version = "0.1.0"
authors = [{name = "Jo√£o Coelho", email = "jojocoelho3@gmail.com"}]
description = "Remove duplicate lines from a file"
dependencies = ["jjcli"]
license = { text = "MIT" }

[project.scripts]
ftk-occ = "ftk.base:main"
ftk-freq = "ftk.freq:main"
